name: Check

on: [push, pull_request]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Vite+
        uses: voidzero-dev/setup-vp@b5d848f4a12639022d2463fda46eacb0a0dcb9ff # v1.0.0
        with:
          cache: true

      - name: Run checks
        run: vp check
